services:
  - type: web
    name: askmaven-frontend
    env: php
    plan: free
    # This rewrite rule is essential for PHP applications.
    # It directs all requests to your index.php file.
    rewrites:
      - source: /*
        destination: /index.php
